version: '3.8'

services:
  backend:
    build: .
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - MONGO_URI=YOUR_MONGO_URI
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - '80:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
